import Header from './components/layout/header/page'
import { ThemeProvider } from './context/ThemeContext'
import './globals.css'

export const metadata = {
  title: 'Viper | SNEKs badass brother',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Header />
          <main className="min-h-screen">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
